export const SET_GAME_OPTS = 'SET_GAME_OPTS';
export const SET_GAME_CODE = 'SET_GAME_CODE';
export const SET_GAME_ITEMS = 'SET_GAME_ITEMS';
export const SET_ITEM_COMPLETE = 'SET_ITEM_COMPLETE';
export const SET_GAME_PLAYERS = 'SET_GAME_PLAYERS';
